### ISSUE TITLE
1000 Degree sword thing has no texture

### ISSUE THREAD

**Issue by TheUnderTaker11** [KodyJKing/RandomToolKit#1]
Its model isn't even rendered in game (aka its a huge purple and black cube). Did you just not set a texture for it or is there a naming error that you can't see in your dev environment? 
EDIT: Using rtk-1.2.5.jar but I checked your changelog and didn't see a fix in the newer version

**Comment by KodyJKing** [comment]
One other person has had this issue. I haven't been able to reproduce it yet and I've tested outside my dev environment in multiple forge installations on multiple machines. Are you using other mods? I'm guessing it might be a compatibility issue with another mod, probably a core mod.

**Comment by TheUnderTaker11** [comment]
Sorry I didn't respond earlier, I completely forgot I left this bug report. I am using these core mods.
 CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  IC2core (industrialcraft-2-2.6.128-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.2.114-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)

**Comment by KodyJKing** [comment]
Thanks UnderTaker, I installed all these mods (I may not have matched minor version numbers) alongside my mod and I didn't get the bug. I've also been using my mod in the DireWolf20 pack without getting this bug.

If you're using a mod pack I could look over the mods in the pack and check for a name collision; Though I suspect it would result in an error not just a bug. A second thing that might help a lot would be if you shared any warnings or error logs you get from starting up Minecraft with all your mods installed. Also this is a silly question, but I'm running out of ideas, what version of forge are you on?

**Comment by TheUnderTaker11** [comment]
I have kept an eye out while I do things, and I haven't done any testing but it might be this mod. https://mods.curse.com/mc-mods/minecraft/235552-levels. No I'm not using a modpack, just a SP world with a bunch of mods. 
This isn't an exact list since I don't keep it updated, but it will probably be close enough https://www.dropbox.com/s/xj3ytc3h8xg5uk3/MyPack%20Mod%20Backups.rar?dl=0

**Comment by GregoriousX** [comment]
I've had this issue too. Removing mcjtylib and CompatLayer fixed this.
