### ISSUE TITLE
Server crash with forge version 12.18.3.2221

### ISSUE THREAD

**Issue by misterfixit** [KodyJKing/RandomToolKit#2]
[crash-2017-02-20_05.58.31-server.txt](https://github.com/KodyJKing/RandomToolKit/files/786669/crash-2017-02-20_05.58.31-server.txt)

**Comment by KodyJKing** [comment]
Thanks for the report. This works on a fresh install of 12.18.3.2221. I think it's a core mod compatibility issue. I have a hard time tracking those down so it might take a while. :/

**Comment by KodyJKing** [comment]
What modpack are you using? If it's a custom modpack, could you make it available?
